export const paperPlaneLoopAbi = [
  {
    type: "function",
    name: "foldPlane",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "landPlane",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "launchPlane",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalFolds",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalLandings",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalLaunches",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userFolds",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userLandings",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userLaunches",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PlaneFolded",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "userFolds",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalFolds",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlaneLanded",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "userLandings",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalLandings",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlaneLaunched",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "userLaunches",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalLaunches",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

